import TKAPemantapanLayout from "@/components/tka/TKAPemantapanLayout";
import type { MateriSection, LatihanSoal } from "@/components/tka/TKAPemantapanLayout";
import { getTkaContohSoal } from "@/data/tkaContohSoal";
import { latihanDasarSVG } from "@/pages/OlimpiadePeluangPage";

const materiSections: MateriSection[] = [
  { heading: "A. Pengertian Peluang", content: `Peluang (probabilitas) adalah ukuran kemungkinan suatu kejadian terjadi.\n\nNotasi: $P(A) = \\dfrac{n(A)}{n(S)}$\n\n- $n(A)$ = banyak kejadian yang diharapkan\n- $n(S)$ = banyak semua kemungkinan (ruang sampel)\n- $0 \\leq P(A) \\leq 1$\n- $P(\\text{pasti terjadi}) = 1$\n- $P(\\text{mustahil}) = 0$` },
  { heading: "B. Ruang Sampel", content: `Ruang sampel (S) = himpunan semua kemungkinan hasil percobaan.\n\nKejadian (A) = bagian dari ruang sampel.\n\nContoh:\n- Melempar dadu: S = {1, 2, 3, 4, 5, 6}, n(S) = 6\n- Melempar koin: S = {A (angka), G (gambar)}, n(S) = 2\n- Melempar 2 koin: S = {AA, AG, GA, GG}, n(S) = 4` },
  { heading: "C. Peluang Komplemen", content: `Peluang komplemen suatu kejadian:\n$P(A^c) = 1 - P(A)$\n\nDimana $A^c$ = kejadian bukan A.` },
  { heading: "D. Peluang Kejadian Majemuk", content: `1. Kejadian saling lepas (mutually exclusive):\n$P(A \\cup B) = P(A) + P(B)$\n\n2. Kejadian tidak saling lepas:\n$P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$\n\n3. Kejadian bebas (independent):\n$P(A \\cap B) = P(A) \\times P(B)$\n\n4. Kejadian bersyarat:\n$P(A|B) = \\dfrac{P(A \\cap B)}{P(B)}$` },
  { heading: "E. Aturan Pencacahan", content: `1. Aturan perkalian: pilihan A cara ada m, pilihan B ada n → total = m × n\n\n2. Permutasi (urutan penting):\n$P(n, r) = \\dfrac{n!}{(n-r)!}$\n\n3. Kombinasi (urutan tidak penting):\n$C(n, r) = \\dfrac{n!}{r!(n-r)!}$\n\n$n! = n \\times (n-1) \\times ... \\times 2 \\times 1$` },
];

const latihanDasar: LatihanSoal[] = [
  { no: 1, soal: "Dari angka 0, 1, 2, 3, 4, 5, 6, akan dibentuk bilangan 3 angka berbeda yang habis dibagi 5. Berapa banyak bilangan yang dapat terbentuk?", options: ["A. 49", "B. 30", "C. 55", "D. 60"] },
  { no: 2, soal: "Berapa banyak susunan huruf dari kata 'MATEMATIKA' jika kedua huruf 'M' tidak boleh bersebelahan?", options: ["A. 120960", "B. 30240", "C. 60480", "D. 151200"] },
  { no: 3, soal: "Lima pasang suami istri (10 orang) akan duduk mengelilingi meja bundar. Berapa banyak cara mereka duduk jika setiap pasangan suami istri harus duduk berdampingan?", options: ["A. 3840", "B. 362880", "C. 120", "D. 768"] },
  { no: 4, soal: "Sebuah delegasi terdiri dari 5 orang akan dipilih dari 6 pria dan 4 wanita. Berapa banyak cara memilih delegasi tersebut jika minimal harus ada 2 wanita dalam delegasi?", options: ["A. 252", "B. 66", "C. 120", "D. 186"] },
  { no: 5, soal: "Seorang siswa harus mengerjakan 8 dari 10 soal ujian. Tetapi, 3 soal pertama (no 1, 2, 3) wajib dikerjakan. Berapa banyak cara siswa tersebut memilih sisa soal yang akan dikerjakan?", options: ["A. 45", "B. 120", "C. 21", "D. 56"] },
  { no: 6, soal: "Di sebuah kelas, ada 30 siswa. 15 siswa suka Matematika, 20 siswa suka Fisika, dan 10 siswa suka Kimia. 8 siswa suka Matematika dan Fisika, 5 siswa suka Fisika dan Kimia, 3 siswa suka Matematika dan Kimia. Jika 2 siswa suka ketiga-tiganya, berapa banyak siswa yang tidak suka satupun dari ketiga pelajaran tersebut?", options: ["A. 0", "B. 3", "C. 1", "D. 2"] },
  { no: 7, soal: "Dalam sebuah kotak terdapat 10 bola merah, 8 bola biru, dan 12 bola hijau. Berapa jumlah minimal bola yang harus diambil (tanpa melihat) untuk menjamin bahwa setidaknya 5 bola berwarna sama telah terambil?", options: ["A. 12", "B. 15", "C. 13", "D. 9"] },
  { no: 8, soal: "Empat orang (A, B, C, D) masing-masing meletakkan topinya di atas meja. Kemudian, masing-masing mengambil satu topi secara acak. Berapa banyak cara sehingga tidak ada satupun orang yang mengambil topinya sendiri?", options: ["A. 24", "B. 9", "C. 8", "D. 6"] },
  { no: 9, soal: "Dalam sebuah pertemuan, setiap orang yang hadir berjabat tangan satu kali dengan setiap orang lainnya. Jika total jabat tangan yang terjadi adalah 120, berapa banyak orang yang hadir di pertemuan tersebut?", options: ["A. 15", "B. 16", "C. 20", "D. 60"] },
  { no: 10, soal: "6 pasang suami istri (total 12 orang) menghadiri sebuah pesta. Mereka semua saling berjabat tangan tepat satu kali dengan orang lain, kecuali dengan pasangan (suami/istri) mereka sendiri. Berapa total jabat tangan yang terjadi?", options: ["A. 30", "B. 55", "C. 60", "D. 66"] },
  { no: 11, soal: "Disediakan angka-angka 0, 1, 2, 3, 4, dan 5. Akan dibentuk bilangan 3 angka (ratusan) yang GENAP, dan angka-angkanya boleh berulang. Berapa banyak bilangan yang dapat terbentuk?", options: ["A. 60", "B. 75", "C. 90", "D. 108"] },
  { no: 12, soal: "Sebuah dadu dilambungkan satu kali. Peluang muncul mata dadu bilangan prima adalah...", options: ["A. $\\frac{1}{6}$", "B. $\\frac{2}{9}$", "C. $\\frac{3}{6}$", "D. $\\frac{4}{6}$"] },
  { no: 13, soal: "Dua buah dadu dilempar bersama-sama, peluang munculnya dadu berjumlah 9 adalah ...", options: ["A. $\\frac{1}{9}$", "B. $\\frac{3}{4}$", "C. $\\frac{1}{4}$", "D. $\\frac{1}{3}$"] },
  { no: 14, soal: "Dalam percobaan melempar 2 buah dadu, peluang muncul mata dadu berjumlah lebih dari 7 adalah ...", options: ["A. $\\frac{1}{18}$", "B. $\\frac{5}{36}$", "C. $\\frac{5}{12}$", "D. $\\frac{7}{18}$"] },
  { no: 15, soal: "Jika dipilih satu huruf dari M A T E M A T I K A, maka peluang yang terpilih huruf A adalah ...", options: ["A. $\\frac{1}{6}$", "B. $\\frac{1}{5}$", "C. $\\frac{1}{4}$", "D. $\\frac{1}{3}$"] },
  { no: 16, soal: "Di dalam sebuah kotak terdapat kelereng sebanyak bernomor 1 sampai dengan 15. Jika dilakukan pengambilan 1 kelereng secara acak dan terambil kelereng bernomor 9, serta kelereng tersebut tidak dikembalikan, maka peluang terambilnya kelereng bernomor ganjil pada pengambilan kedua adalah ...", options: ["A. $\\frac{8}{14}$", "B. $\\frac{7}{14}$", "C. $\\frac{8}{15}$", "D. $\\frac{7}{15}$"] },
  { no: 17, soal: "Dalam sebuah kantong terdapat bola bernomor 1 sampai dengan 13. Bola merah bernomor 1 sampai dengan 4, bola biru bernomor 5 sampai dengan 8 dan sisanya bola putih. Dari kantong tersebut diambil sebuah bola secara acak dan terambil bola biru. Peluang terambilnya bola bernomor kelipatan tiga dan berwarna putih pada pengambilan kedua adalah ...", options: ["A. $\\frac{1}{2}$", "B. $\\frac{1}{5}$", "C. $\\frac{1}{6}$", "D. $\\frac{2}{13}$"] },
  { no: 18, soal: "Pada seleksi pegawai sebuah perusahaan, seorang calon dapat diterima apabila lulus tes akademik dan tes fisik. Dari hasil seleksi, 25 lulus tes akademik, 20 lulus tes fisik dan 15 orang lulus keduanya. Saat pengumuman peserta tes dipanggil satu-persatu. Peluang terpanggil peserta yang hanya lulus tes fisik adalah ...", options: ["A. $\\frac{5}{6}$", "B. $\\frac{2}{3}$", "C. $\\frac{1}{2}$", "D. $\\frac{1}{6}$"] },
  { no: 19, soal: "Tiga mata uang ditos bersama-sama. Peluang munculnya dua angka dan satu gambar adalah ...", options: ["A. $\\frac{3}{4}$", "B. $\\frac{2}{4}$", "C. $\\frac{3}{8}$", "D. $\\frac{2}{8}$"] },
  { no: 20, soal: "Dalam percobaan melempar 3 uang logam secara bersamaan, peluang muncul minimal 2 angka adalah...", options: ["A. 0,375", "B. 0,500", "C. 0,667", "D. 0,875"] },
  { no: 21, soal: "Roni diperbolehkan ibunya untuk mengambil 1 permen dari sebuah kantong. Dia tidak dapat melihat warna permen tersebut. Kantong tersebut berisi 4 permen merah, 2 permen biru, 8 permen kuning, dan 6 permen hijau. Berapa peluang Roni mengambil sebuah permen warna merah?", options: ["A. 10%", "B. 20%", "C. 25%", "D. 50%"] },
  { no: 22, soal: "Di dalam kaleng terdapat 8 buah bola yang bernomor 1, 2, 3, 4, 5, 6, 7, 8. Jika diambil secara acak 2 bola sekaligus dari kaleng tersebut, peluang yang terambil kedua bola tersebut bernomor genap adalah …", options: ["A. $\\frac{1}{7}$", "B. $\\frac{2}{7}$", "C. $\\frac{3}{14}$", "D. $\\frac{3}{7}$"] },
  { no: 23, soal: "Terdapat 5 buah bola yang diberi nomor 1, 2, 3, 4, dan 5. Jika diambil 2 buah bola sekaligus, maka peluang terambil kedua bola bernomor ganjil adalah …", options: ["A. $\\frac{1}{5}$", "B. $\\frac{3}{10}$", "C. $\\frac{2}{5}$", "D. $\\frac{1}{2}$"] },
  { no: 24, soal: "Bima ingin menulis bilangan yang terdiri dari dua angka dari angka-angka 1, 2, 3, 5, 8, 9. Jika tidak ada angka yang sama, banyak bilangan dengan nilai berbeda yang bisa ditulis seluruhnya adalah ....", options: ["A. 20", "B. 24", "C. 30", "D. 36"] },
  { no: 25, soal: "Pada pelemparan dua dadu, peluang muncul mata dadu berjumlah 5 atau 7 adalah ...", options: ["A. 0,14", "B. 0,16", "C. 0,17", "D. 0,28"] },
  { no: 26, soal: "Sebuah dadu dan mata uang logam ditos bersama-sama. Peluang munculnya mata uang logam muncul gambar dan dadu lebih dari 4 adalah ....", options: ["A. $\\frac{1}{12}$", "B. $\\frac{1}{6}$", "C. $\\frac{1}{4}$", "D. $\\frac{1}{3}$"] },
  { no: 27, soal: "Dari seperangkat kartu bridge (52 kartu), diambil sebuah kartu secara acak. Peluang yang terambil kartu As adalah ....", options: ["A. $\\frac{1}{52}$", "B. $\\frac{1}{26}$", "C. $\\frac{1}{13}$", "D. $\\frac{4}{13}$"] },
  { no: 28, soal: "Sebuah dadu ditos sebanyak 60 kali. Frekuensi harapan munculnya angka kurang dari 3 adalah ....", options: ["A. 15 kali", "B. 20 kali", "C. 30 kali", "D. 35 kali"] },
  { no: 29, soal: "Sebuah bola diambil dari sebuah kantong yang berisi 4 bola berwarna putih, 6 bola berwarna hijau, dan 5 bola berwarna merah. Peluang terambilnya bola berwarna merah adalah ...", options: ["A. $\\frac{1}{5}$", "B. $\\frac{4}{15}$", "C. $\\frac{1}{3}$", "D. $\\frac{3}{5}$"] },
  { no: 30, soal: "Tiga keping uang logam dilempar bersama-sama. Peluang muncul ketiganya gambar adalah ...", options: ["A. $\\frac{1}{8}$", "B. $\\frac{1}{4}$", "C. $\\frac{3}{8}$", "D. $\\frac{1}{2}$"] },
  { no: 31, soal: "Sebuah dadu dilambungkan satu kali. Peluang munculnya mata dadu kurang dari 4 adalah ...", options: ["A. $\\frac{1}{6}$", "B. $\\frac{1}{3}$", "C. $\\frac{1}{2}$", "D. $\\frac{2}{3}$"] },
  { no: 32, soal: "Seorang ibu dan anaknya bermain tebak warna dengan cara mengambil bola dari kotak A dan memasukkannya ke kotak B. Kotak A berisi 5 bola merah, 7 bola kuning, dan 3 bola biru, sedangkan kotak B berisi 3 bola merah, 5 bola kuning, dan 3 bola biru. Ibu mengambil satu bola dari kotak A dan memasukkannya ke kotak B, kemudian si anak mengambil satu bola dari kotak B. Peluang si anak mendapatkan bola biru adalah ...", options: ["A. $\\frac{3}{11}$", "B. $\\frac{4}{15}$", "C. $\\frac{1}{4}$", "D. $\\frac{1}{3}$"] },
  { no: 33, soal: "Sebuah keluarga ingin mempunyai 4 orang anak. Peluang bahwa keluarga tersebut memiliki paling banyak 2 orang anak laki-laki adalah ...", options: ["A. $\\frac{5}{16}$", "B. $\\frac{6}{16}$", "C. $\\frac{11}{16}$", "D. $\\frac{13}{16}$"] },
  { no: 34, soal: "Babak perempat final Liga Champion diikuti oleh 8 tim A, B, C, D, E, F, G, dan H. Setiap tim memiliki peluang $\\frac{1}{2}$ untuk melaju ke babak selanjutnya. Jika B dan F berada di bagian bracket yang berbeda, peluang B bertemu F di babak final dan F menjadi juara adalah ...", options: ["A. $\\frac{1}{8}$", "B. $\\frac{1}{16}$", "C. $\\frac{1}{32}$", "D. $\\frac{1}{64}$"] },
  { no: 35, soal: "Seorang siswa mempunyai tiga buah celana berwarna biru, hitam, dan abu-abu, tiga buah kemeja berwarna putih, hijau, dan kuning serta dua pasang sepatu berwarna hitam dan coklat. Banyak kombinasi pakaian dan sepatu yang bisa digunakan siswa tersebut adalah ... kombinasi.", options: ["A. 12", "B. 15", "C. 18", "D. 24"] },
  { no: 36, soal: "Dalam sebuah peti terdapat 7 bola kuning bernomor 1−7, dan 5 bola merah bernomor a−e. Jika seseorang mengambil sebuah bola dari dalam peti secara acak, peluang terambilnya bola kuning bernomor ganjil atau bola merah dengan huruf vokal adalah ...", options: ["A. $\\frac{1}{4}$", "B. $\\frac{1}{3}$", "C. $\\frac{5}{12}$", "D. $\\frac{1}{2}$"] },
  { no: 37, soal: "Sebuah kantong berisi 5 kelereng merah, 6 kelereng kuning, dan 9 kelereng hijau. Sebuah kelereng diambil dari kantong tersebut. Peluang terambil kelereng kuning adalah ...", options: ["A. $\\frac{1}{4}$", "B. $\\frac{3}{10}$", "C. $\\frac{9}{20}$", "D. $\\frac{3}{5}$"] },
  { no: 38, soal: "Dalam rangka memperingati Hari Kemerdekaan RI, panitia menyiapkan sebuah kotak berisi kartu yang diberi nomor 1 sampai dengan 30. Setiap peserta hanya boleh mengambil satu kartu, dan yang mendapatkan kartu bernomor kelipatan 3 atau bilangan prima akan mendapat hadiah doorprize. Berapakah peluang seorang murid akan mendapatkan doorprize?", options: ["A. $\\frac{7}{15}$", "B. $\\frac{17}{30}$", "C. $\\frac{19}{30}$", "D. $\\frac{2}{3}$"] },
  { no: 39, soal: "Sebuah survei mengambil secara acak 60 murid sebagai sampelnya. Hasilnya, 36 siswa menjawab membawa bekal ke sekolah. Jika survei dilakukan lagi pada 50 murid lainnya dan diperkirakan hasil survei sama proporsinya dengan survei sebelumnya, frekuensi relatif murid yang membawa bekal dari seluruh siswa yang disurvei adalah ....", options: ["A. 0,59", "B. 0,60", "C. 0,61", "D. 0,62"] },
  { no: 40, soal: "Tiga buah dadu biasa dilempar sekaligus sebanyak satu kali. Peluang salah satu mata dadu sama dengan jumlah dua mata dadu lainnya adalah …", options: ["A. $\\frac{1}{6}$", "B. $\\frac{5}{24}$", "C. $\\frac{7}{24}$", "D. $\\frac{1}{3}$"] },
];

const PeluangPage = () => (
  <TKAPemantapanLayout
    title="PELUANG"
  materiSections={materiSections}
  contohSoal={getTkaContohSoal("peluang")}
  latihanDasar={latihanDasar}
    gambarMap={latihanDasarSVG}
  />
);

export default PeluangPage;
