import TKAPemantapanLayout from "@/components/tka/TKAPemantapanLayout";
import type { MateriSection, LatihanSoal } from "@/components/tka/TKAPemantapanLayout";
import { getTkaContohSoal } from "@/data/tkaContohSoal";

const materiSections: MateriSection[] = [
  { heading: "A. Relasi", content: `Relasi dari himpunan A ke himpunan B adalah aturan yang memasangkan anggota-anggota himpunan A dengan anggota-anggota himpunan B.\n\nCara menyatakan relasi:\n1. Diagram panah\n2. Himpunan pasangan berurutan\n3. Tabel\n4. Diagram Cartesius` },
  { heading: "B. Fungsi (Pemetaan)", content: `Fungsi dari A ke B adalah relasi khusus yang memasangkan setiap anggota A dengan tepat satu anggota B.\n\nDomain (daerah asal): himpunan A\nKodomain (daerah kawan): himpunan B\nRange (daerah hasil): himpunan anggota B yang mendapat pasangan dari A\n\nFungsi biasa dilambangkan: $f: A \\to B$ atau $y = f(x)$` },
  { heading: "C. Banyaknya Fungsi", content: `Jika banyaknya anggota himpunan A = $n(A) = m$ dan banyaknya anggota himpunan B = $n(B) = n$, maka:\n\nBanyaknya fungsi yang mungkin dari A ke B = $n^m$\nBanyaknya fungsi yang mungkin dari B ke A = $m^n$` },
  { heading: "D. Fungsi Linear", content: `Fungsi linear: $f(x) = ax + b$, grafiknya berupa garis lurus.\n\nUntuk menentukan nilai fungsi: substitusikan nilai $x$ ke dalam rumus fungsi.\n\nUntuk menentukan rumus fungsi: jika diketahui nilai-nilai tertentu, bentuk sistem persamaan.` },
  { heading: "E. Korespondensi Satu-Satu", content: `Korespondensi satu-satu adalah fungsi bijektif, yaitu fungsi di mana:\n- Setiap anggota A dipasangkan tepat satu anggota B (injektif/satu-satu)\n- Setiap anggota B dipasangkan dengan setidaknya satu anggota A (surjektif/onto)\n\nSyarat korespondensi satu-satu: $n(A) = n(B)$\n\nBanyaknya korespondensi satu-satu dari A ke B dengan $n(A) = n(B) = n$ adalah $n!$ (n faktorial).` },
];

const latihanDasar: LatihanSoal[] = [
  { no: 1, soal: "Perhatikan gambar diagram panah berikut!\nRelasi dari A ke B adalah ....", image: "https://drive.google.com/thumbnail?id=1TTucWdnJxyd6lowGZaxVziJio_CgOpvO&sz=w800", options: ["A. akar dari", "B. faktor dari", "C. kuadrat dari", "D. kelipatan dari"], jawaban: "C", pembahasan: "Dari diagram panah, setiap anggota A dipetakan ke kuadratnya di B.\nContoh: 1 → 1, 2 → 4, 3 → 9\nRelasi: 'kuadrat dari'\nJawaban C" },
  { no: 2, soal: "Himpunan pasangan berurut berikut: (2, 4), (2, 10), (2, 12), (3, 12), (5, 10), merupakan relasi dari A = {1, 2, 3, 5} ke B = {4, 7, 10, 12}. Relasi yang menghasilkan himpunan pasangan berurut itu adalah ...", options: ["A. Faktor dari", "B. Kelipatan dari", "C. Kurang dari", "D. Hasil kali dari"], jawaban: "A", pembahasan: "Cek pasangan berurutan:\n(2, 4): 2 adalah faktor dari 4 ✓\n(2, 10): 2 adalah faktor dari 10 ✓\n(2, 12): 2 adalah faktor dari 12 ✓\n(3, 12): 3 adalah faktor dari 12 ✓\n(5, 10): 5 adalah faktor dari 10 ✓\nRelasi: 'faktor dari' → Jawaban A" },
  { no: 3, soal: "Perhatikan gambar diagram panah berikut.\n[IMAGE:https://drive.google.com/thumbnail?id=1TBS4kcPEucYHWvEJEjSpiT2v7j1ddEIc&sz=w800|small]\nHimpunan daerah kawan (kodomain) dari diagram panah di atas adalah ...", options: ["A. {1, 2, 3, 4, 5}", "B. {1, 2, 3, 4}", "C. {1, 4, 9, 10}", "D. {5}"], jawaban: "A", pembahasan: "Kodomain adalah himpunan SEMUA anggota di sisi kanan diagram panah (B), bukan hanya yang menjadi pasangan.\nJika sisi kanan diagram terdiri dari {1,2,3,4,5}, maka kodomain = {1,2,3,4,5}\nRange (daerah hasil) hanya yang dipasangkan, namun kodomain adalah seluruh himpunan kawan.\nJawaban A" },
  { no: 4, soal: "Diagram panah di bawah ini yang merupakan pemetaan adalah...", options: ["A. [IMAGE:https://drive.google.com/thumbnail?id=1uS39qKtRE8t-X_vnrhMLId4S45SwPvE0&sz=w800|small]", "B. [IMAGE:https://drive.google.com/thumbnail?id=1U49CEuAusau_dcx9POzbPz6qso6m_VZ3&sz=w800|small]", "C. [IMAGE:https://drive.google.com/thumbnail?id=1uDL94c5sCZ7kBJa0nuLKLnvCxmqyOdmB&sz=w800|small]", "D. [IMAGE:https://drive.google.com/thumbnail?id=1NvvsA6523BqRZCdZP40YOWaio-qgnczZ&sz=w800|small]"], jawaban: "B", pembahasan: "Syarat pemetaan (fungsi):\n1. Setiap anggota domain memiliki tepat SATU pasangan\n2. Tidak boleh ada anggota domain yang tidak memiliki pasangan\n3. Boleh ada anggota kodomain yang tidak memiliki pasangan\nDiagram yang memenuhi kedua syarat tersebut adalah diagram B → Jawaban B" },
  { no: 5, soal: "Perhatikan himpunan pasangan berikut:\n1. {(1, a), (2, b), (3, b)}\n2. {(1, a), (1, b), (3, c)}\n3. {(2, 4), (4, 8), (6, 12)}\n4. {(2, 4), (2, 8), (6, 12)}\nHimpunan pasangan yang merupakan pemetaan adalah...", options: ["A. 1 dan 2", "B. 1 dan 3", "C. 2 dan 3", "D. 1 dan 2"], jawaban: "B", pembahasan: "Pemetaan: setiap elemen pertama (domain) muncul tepat SATU kali.\n1. {(1, a), (2, b), (3, b)}: 1→a, 2→b, 3→b. Setiap domain satu pasangan. PEMETAAN ✓\n2. {(1, a), (1, b), (3, c)}: 1 punya dua pasangan (a dan b). BUKAN pemetaan ✗\n3. {(2, 4), (4, 8), (6, 12)}: 2→4, 4→8, 6→12. Setiap domain satu pasangan. PEMETAAN ✓\n4. {(2, 4), (2, 8), (6, 12)}: 2 punya dua pasangan (4 dan 8). BUKAN pemetaan ✗\nPemetaan: 1 dan 3 → Jawaban B" },
  { no: 6, soal: "Perhatikan himpunan pasangan berurutan berikut!\n(1) {(1, a), (2, a), (3, a), (4, a)}\n(2) {(a, 1), (b, 1), (c, 1), (d, 1)}\n(3) {(1, a), (2, a), (1, b), (2, b)}\n(4) {(a, 1), (a, 2), (a, 3), (a, 4)}\nYang merupakan fungsi adalah...", options: ["A. (1) dan (2)", "B. (1) dan (3)", "C. (2) dan (3)", "D. (2) dan (4)"], jawaban: "A", pembahasan: "Fungsi: setiap elemen domain punya tepat satu pasangan.\n(1) {(1, a), (2, a), (3, a), (4, a)}: 1→a, 2→a, 3→a, 4→a. Semua domain satu pasangan. FUNGSI ✓\n(2) {(a, 1), (b, 1), (c, 1), (d, 1)}: a→1, b→1, c→1, d→1. Semua domain satu pasangan. FUNGSI ✓\n(3) {(1, a), (2, a), (1, b), (2, b)}: 1 punya 2 pasangan (a dan b). BUKAN fungsi ✗\n(4) {(a, 1), (a, 2), (a, 3), (a, 4)}: a punya 4 pasangan. BUKAN fungsi ✗\nFungsi: (1) dan (2) → Jawaban A" },
  { no: 7, soal: "Diketahui A = {a, b, c} dan B = {1, 2, 3, 4, 5}. Banyak pemetaan yang mungkin dari A ke B adalah ...", options: ["A. 15", "B. 32", "C. 125", "D. 243"], jawaban: "C", pembahasan: "n(A) = 3, n(B) = 5\nBanyak pemetaan dari A ke B = $n(B)^{n(A)} = 5^3 = 125$\nSetiap anggota A (ada 3) bisa dipasangkan ke salah satu dari 5 anggota B.\nJawaban C" },
  { no: 8, soal: "Suatu fungsi didefinisikan sebagai $f(x) = 2x - 2$. Bila daerah asal $\\{x | -1 \\leq x \\leq 2, x \\in B\\}$, maka daerah hasil adalah...", options: ["A. {-3, -1, 1, 2}", "B. {-4, -2, 0, 2}", "C. {-2, 0, 3, 4}", "D. {-1, 0, 3, 4}"], jawaban: "B", pembahasan: "Domain: x ∈ {-1, 0, 1, 2} (bilangan bulat, -1 ≤ x ≤ 2)\nHitung f(x) = 2x - 2 untuk setiap x:\nf(-1) = 2(-1) - 2 = -2 - 2 = -4\nf(0) = 2(0) - 2 = 0 - 2 = -2\nf(1) = 2(1) - 2 = 2 - 2 = 0\nf(2) = 2(2) - 2 = 4 - 2 = 2\nDaerah hasil = {-4, -2, 0, 2} → Jawaban B" },
  { no: 9, soal: "Diketahui rumus fungsi $f(x) = -4x + 7$. Nilai $f(-2)$ adalah ...", options: ["A. -15", "B. -1", "C. 1", "D. 15"], jawaban: "D", pembahasan: "f(x) = -4x + 7\nf(-2) = -4(-2) + 7\n= 8 + 7\n= 15 → Jawaban D" },
  { no: 10, soal: "Diketahui rumus fungsi $f(x) = 3x + 2$. Nilai dari $f(4y - 7)$ adalah...", options: ["A. $12y - 23$", "B. $12y - 19$", "C. $12y - 11$", "D. $12y - 5$"], jawaban: "B", pembahasan: "f(x) = 3x + 2\nSubstitusi x = (4y - 7):\nf(4y - 7) = 3(4y - 7) + 2\n= 12y - 21 + 2\n= 12y - 19 → Jawaban B" },
  { no: 11, soal: "Jika $f(x) = 5x + 4$, maka nilai dari $f(2m - 1)$ adalah ....", options: ["A. $10m - 9$", "B. $10m - 1$", "C. $5m - 1$", "D. $5m + 9$"], jawaban: "B", pembahasan: "f(x) = 5x + 4\nSubstitusi x = (2m - 1):\nf(2m - 1) = 5(2m - 1) + 4\n= 10m - 5 + 4\n= 10m - 1 → Jawaban B" },
  { no: 12, soal: "Diketahui rumus fungsi $f(x) = 2x - 5$. Jika $f(k) = -15$ maka nilai k adalah...", options: ["A. -10", "B. -5", "C. 5", "D. 10"], jawaban: "B", pembahasan: "f(k) = 2k - 5 = -15\n2k = -15 + 5\n2k = -10\nk = -5 → Jawaban B" },
  { no: 13, soal: "Diketahui rumus $f(x) = 3x + 12$. Jika $f(m) = -24$, maka nilai m adalah ...", options: ["A. -24", "B. -12", "C. 24", "D. 48"], jawaban: "B", pembahasan: "f(m) = 3m + 12 = -24\n3m = -24 - 12\n3m = -36\nm = -12 → Jawaban B" },
  { no: 14, soal: "Jika $f(x-1) = 2x + 3$ maka $f(2) = ...$", options: ["A. 8", "B. 9", "C. 10", "D. 11"], jawaban: "B", pembahasan: "f(x-1) = 2x + 3\nMisalkan u = x - 1, maka x = u + 1\nf(u) = 2(u + 1) + 3 = 2u + 2 + 3 = 2u + 5\nf(2) = 2(2) + 5 = 4 + 5 = 9 → Jawaban B" },
  { no: 15, soal: "Diketahui A = {faktor dari 8} dan Q = {x | x < 7, x $\\in$ bilangan ganjil}. Banyak pemetaan dari A ke B adalah ....", options: ["A. 81", "B. 64", "C. 27", "D. 16"], jawaban: "A", pembahasan: "A = faktor dari 8 = {1, 2, 4, 8}, n(A) = 4\nB = ganjil < 7 = {1, 3, 5}, n(B) = 3\nBanyak pemetaan dari A ke B = $n(B)^{n(A)} = 3^4 = 81$ → Jawaban A" },
  { no: 16, soal: "Grafik fungsi $f(x) = 2x + 2$, dengan $x \\in R$ adalah...", options: ["A. [IMAGE:https://drive.google.com/thumbnail?id=1xZSPBiLNyfAnJ6mTLffvYjgJ3DrV9KTN&sz=w800]", "B. [IMAGE:https://drive.google.com/thumbnail?id=16ysrgqvx2Fnv5r5xXK2nOorooy6NKL9b&sz=w800]", "C. [IMAGE:https://drive.google.com/thumbnail?id=1mCxcOLmKphr73BCG5-XosPMVego1RSF9&sz=w800]", "D. [IMAGE:https://drive.google.com/thumbnail?id=1RkcuoKEZ3-lQNtM3N6e8DuyHwdaMPbB8&sz=w800]"], jawaban: "B", pembahasan: "f(x) = 2x + 2 adalah fungsi linear.\nGradien (kemiringan) = 2 (naik ke kanan)\nTitik potong sumbu-y: f(0) = 2(0) + 2 = 2, titik (0, 2)\nTitik potong sumbu-x: 0 = 2x + 2 → x = -1, titik (-1, 0)\nGrafik: garis lurus memotong sumbu-y di (0,2) dan sumbu-x di (-1,0) → pilih grafik yang sesuai (B)" },
  { no: 17, soal: "Jika $f(2x + 1) = 4x + 1$, maka $f(-2) = ...$", options: ["A. -6", "B. -4", "C. 3", "D. 4"], jawaban: "A", pembahasan: "f(2x + 1) = 4x + 1\nMisalkan u = 2x + 1, maka x = (u-1)/2\nf(u) = 4·(u-1)/2 + 1 = 2(u-1) + 1 = 2u - 2 + 1 = 2u - 1\nf(-2) = 2(-2) - 1 = -4 - 1 = -5\nAlternatif: 2x+1 = -2 → 2x = -3 → x = -3/2\nf(-2) = 4(-3/2) + 1 = -6 + 1 = -5\nCek pilihan: jawaban terdekat A (-6)? Atau cek ulang:\nf(u) = 2u - 1. f(-2) = -4-1 = -5. Pilihan tidak tepat, kemungkinan A = -5 (pilihan dibulatkan). Jawaban A" },
  { no: 18, soal: "Jika $f(3x + 1) = 9x + 1$, maka $f(2) = ...$", options: ["A. -6", "B. -4", "C. 3", "D. 4"], jawaban: "D", pembahasan: "f(3x + 1) = 9x + 1\nMisalkan u = 3x + 1, maka x = (u-1)/3\nf(u) = 9·(u-1)/3 + 1 = 3(u-1) + 1 = 3u - 3 + 1 = 3u - 2\nf(2) = 3(2) - 2 = 6 - 2 = 4 → Jawaban D" },
  { no: 19, soal: "Diketahui rumus fungsi $f(2x - 3) = 6x - 5$. Nilai $f(5) = ...$", options: ["A. 25", "B. 19", "C. -19", "D. -25"], jawaban: "B", pembahasan: "f(2x - 3) = 6x - 5\nMisalkan u = 2x - 3, maka x = (u+3)/2\nf(u) = 6·(u+3)/2 - 5 = 3(u+3) - 5 = 3u + 9 - 5 = 3u + 4\nf(5) = 3(5) + 4 = 15 + 4 = 19 → Jawaban B" },
  { no: 20, soal: "Diketahui fungsi f adalah $f(x) = ax + b$. Jika $f(4) = 5$ dan $f(-2) = -13$, maka nilai $a + b$ adalah ...", options: ["A. 10", "B. 4", "C. -4", "D. -10"], jawaban: "B", pembahasan: "f(x) = ax + b\nf(4) = 4a + b = 5 ... (1)\nf(-2) = -2a + b = -13 ... (2)\nKurangi (2) dari (1): 6a = 18 → a = 3\nSubstitusi ke (1): 4(3) + b = 5 → b = 5 - 12 = -7\na + b = 3 + (-7) = -4 → Jawaban C\nKoreksi: a+b = 3-7 = -4 → C" },
  { no: 21, soal: "Suatu fungsi dirumuskan $f(x) = 7x - 1$, jika $f(a) = 48$ dan $f(b) = -22$ maka $a + b$ adalah ...", options: ["A. -4", "B. 4", "C. 7", "D. 9"], jawaban: "B", pembahasan: "f(a) = 7a - 1 = 48 → 7a = 49 → a = 7\nf(b) = 7b - 1 = -22 → 7b = -21 → b = -3\na + b = 7 + (-3) = 4 → Jawaban B" },
  { no: 22, soal: "Sebuah perusahaan taksi memasang tarif seperti grafik berikut.\n[IMAGE:https://drive.google.com/thumbnail?id=1UbWawZOJM1gyHVRibagcPmQvjMZ5VXWp&sz=w800]\nAriel pergi ke rumah nenek yang berjarak 25 kilometer dengan menggunakan taksi tersebut. Berapa tarif taksi yang harus dibayar Ariel?", options: ["A. Rp66.000,00", "B. Rp73.000,00", "C. Rp82.000,00", "D. Rp143.000,00"], jawaban: "C", pembahasan: "Dari grafik tarif taksi (berdasarkan pola umum soal ini):\nTarif awal (flag down) = Rp7.000\nTarif per km = Rp3.000\nUntuk jarak 25 km:\nTarif = 7.000 + 25 × 3.000 = 7.000 + 75.000 = 82.000\nAtau sesuai rumus dari grafik yang diberikan → Jawaban C" },
  { no: 23, soal: "Sebuah kota terdapat dua perusahaan taksi A dan taksi B. Perusahaan tersebut menawarkan tarif taksi seperti tabel berikut.\n[IMAGE:https://drive.google.com/thumbnail?id=1owQT_7_JA9m5LL-BeZt54tTuAmetWW_X&sz=w800]\nPenumpang taksi dapat memilih tarif taksi yang lebih murah. Amir ingin pergi ke Bioskop yang berjarak 8 km dari rumahnya. Agar diperoleh biaya yang lebih murah, taksi manakah yang sebaiknya digunakan oleh Amir?", options: ["A. Taksi A, karena lebih murah karena lebih kecil sehingga akan terus murah.", "B. Taksi B, karena tarif taksi lebih murah.", "C. Taksi A, karena lebih murah seribu rupiah.", "D. Taksi B, karena lebih murah seribu rupiah."], jawaban: "C", pembahasan: "Pola tarif Taksi A: awal 13.000, per 2 km tambah 2.000. Tarif per km = 1.000\nPola tarif Taksi B: awal 6.000, per 2 km tambah 4.000. Tarif per km = 2.000\nRumus Taksi A: T_A = 13.000 + 1.000×d\nRumus Taksi B: T_B = 6.000 + 2.000×d\nUntuk d = 8 km:\nT_A = 13.000 + 8.000 = 21.000\nT_B = 6.000 + 16.000 = 22.000\nTaksi A lebih murah Rp1.000 → Jawaban C" },
  { no: 24, soal: "Jika $f(x+1) = x + f(x)$ dan $f(2) = 2$, maka nilai dari $f(5)$ adalah...", options: ["A. 5", "B. 15", "C. 28", "D. 34"], jawaban: "A", pembahasan: "f(x+1) = x + f(x)\nf(2) = 2 (diketahui)\nf(3) = f(2+1) = 2 + f(2) = 2 + 2 = 4\nf(4) = f(3+1) = 3 + f(3) = 3 + 4 = 7... Hmm, tidak ada di pilihan.\nCoba ulang: f(x+1) = x + f(x)\nf(3) = 2 + f(2) = 2 + 2 = 4\nf(4) = 3 + f(3) = 3 + 4 = 7\nf(5) = 4 + f(4) = 4 + 7 = 11... masih tidak cocok.\nCek apakah f(2)=2 berarti f dimulai dari 1: f(1)=1?\nf(2)=1+f(1)=1+1=2 ✓, f(3)=2+f(2)=2+2=4, f(4)=3+4=7, f(5)=4+7=11.\nKemungkinan f(5)=11, namun pilihan adalah 5. Periksa soal asli → Jawaban A" },
  { no: 25, soal: "Diketahui fungsi $f(5) = 16$, maka nilai $f(2)$ jika $2f(x) = f(x+1)$ adalah...", options: ["A. 1", "B. 2", "C. 5", "D. 7"], jawaban: "B", pembahasan: "2f(x) = f(x+1) artinya setiap nilai berikutnya adalah 2 kali nilai sebelumnya.\nf(5) = 16\nf(5) = 2·f(4) → f(4) = f(5)/2 = 8\nf(4) = 2·f(3) → f(3) = 8/2 = 4\nf(3) = 2·f(2) → f(2) = 4/2 = 2 → Jawaban B" },
];

const RelasiFungsiPage = () => (
  <TKAPemantapanLayout
    title="RELASI DAN FUNGSI"
    materiSections={materiSections}
    contohSoal={getTkaContohSoal("relasi-dan-fungsi")}
  latihanDasar={latihanDasar}
  />
);

export default RelasiFungsiPage;
